[build-system]
requires = ["setuptools>=82"]
build-backend = "setuptools.build_meta"

[project]
name = "pydag"
version = "0.0.1"
description = "An IIoT framework for reading and writing from sources/sinks."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
keywords = ["IIoT", "Industrial Datalogging", "software robots", "data agents"]
authors = [
  { name = "Jonas Hillenbrand", email = "hillenbrandjonas@hotmail.com" },
  { name = "2Obe", email = "twoobe.mail@gmail.com" }
]
classifiers = [
  "Development Status :: 2 - Experimental",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11"
]
dependencies = [
    "matplotlib",
    "loguru",
    "PyYAML",
    "numpy",
    "pandas",
    "fastapi[standard]",
    "APScheduler",
    "pwdlib", 
    "pwdlib[argon2]",
]

[project.optional-dependencies]
ui = [  
    "graphviz", 
    "nicegui",
    "plotly"
]

iiot = [
   "opcua",
    "pyads",
    "sounddevice",
    "paho-mqtt",
    "urllib3",
    "jsonpath-ng",
    "python-snap7",
    "websocket-client",
    "pyserial",
]

docs = [
  "openpyxl",
  "pypdf",
  "PyMuPDF",
  "unstructured[all-docs]",
  "watchdog",
  "vobject",
  "psutil",
  "docxtpl",
  "bs4",
  "lxml",
]

office = [
    "msal",
]

browser = [
  "selenium",
]

cad = [  
  "cadquery",
  "cq-editor",
]

db = [
  "influxdb-client",
  "pyodbc",
]

dsp = [    
  "numba",
  "torch",
  "sktime",
  "seaborn",
  "tirex-ts @ git+https://github.com/NX-AI/tirex",
  "chronos-forecasting",
  "librosa",
]

ocr = [
  "pdf2image",
  "pytesseract",
  "pillow",
]

sap = []

llm = [
  "langchain-ollama",
  "langchain-chroma",
  "langchain_mistralai",
  "langchain-unstructured",
  "langchain-tavily<0.2",
  "langchain[huggingface,openai,all]",
  "sentence-transformers",
  "langchain_text_splitters",
  "langchain_community",
  "langgraph>=1.0.10",
  "hf_xet",
  "mistralai",
  "spacy",
]

sim = [
  "ross-rotordynamics",
  "EasyFEA",
]

test = [
  "pytest",
  "pytest-asyncio",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pydag", "pydag.*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"pydag" = ["services/plot/*.html", "_docs/element_icons/**/*"]

[project.urls]
Documentation = "https://github.com/PyDataAgents/PyDataAgents.git"
Issues = "https://github.com/PyDataAgents/PyDataAgents.git"
Source = "https://github.com/PyDataAgents/PyDataAgents.git"
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
filterwarnings = [
    "ignore:Failed to initialize NumPy.*_ARRAY_API not found.*:UserWarning:transformers\\.cache_utils",
    "ignore:datetime\\.datetime\\.utcfromtimestamp\\(\\) is deprecated and scheduled for removal.*:DeprecationWarning:reactivex\\.internal\\.constants",
    "ignore:'pkgutil\\.find_loader' is deprecated and slated for removal in Python 3\\.14.*:DeprecationWarning:pytesseract\\.pytesseract",
]
