[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pydatagrabber"
version = "v0.0.1a5"
description = "An IIoT framework for reading and writing from sources/sinks."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = ["IIoT", "Industrial Datalogging", "software robots", "data agents"]
authors = [
  { name = "Jonas Hillenbrand", email = "hillenbrandjonas@hotmail.com" },
]
classifiers = [
  "Development Status :: 2 - Experimental",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11"
]
dependencies = [
    "loguru",
    "opcua",
    "pyads",
    "fastapi[standard]",
    "PyYAML",
    "sounddevice",
    "numpy",
    "paho-mqtt",
    "urllib3",
    "jsonpath-ng",
    "influxdb-client",
    "python-snap7",
    "APScheduler",
    "websocket-client",
    "selenium",
    "requests_ntlm",
    "openpyxl",
    "pyodbc",
    "langchain",
    "openai",
    "chromadb",
    "sentence-transformers",
    "pypdf",
    "unstructured"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pydatagrabber*"]
exclude = ["tests"]

[project.urls]
Documentation = "https://github.com/jhillenbrand/PyDataGrabber"
Issues = "https://github.com/jhillenbrand/PyDataGrabber"
Source = "https://github.com/jhillenbrand/PyDataGrabber"